services:
  db:
    image: postgres:15
    container_name: storefront_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: tareq
      POSTGRES_PASSWORD: tareq
      POSTGRES_DB: storefront
    ports:
      - "5434:5432"
    volumes:
      - storefront_data:/var/lib/postgresql
volumes:
  storefront_data: